{{- if .Values.logaggregator.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-log-aggregator
  namespace: {{ .Release.Namespace }}
spec:
  selector:
    app: {{ .Release.Name }}-log-aggregator
  ports:
    - protocol: TCP
      port: {{ .Values.logaggregator.port }}
      targetPort: {{ .Values.logaggregator.port }}
  type: ClusterIP
{{- end }}
