{{- if .Values.ui.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-ui
  namespace: {{ .Release.Namespace }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Release.Name }}-ui
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-ui
    spec:
      containers:
        - name: {{ .Release.Name }}-ui
          image: {{ .Values.ui.image.repository }}:{{ .Values.ui.image.tag }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          env:
            - name: VITE_API_URL
              value: https://{{ .Values.global.hosts.api }}
          imagePullPolicy: Always
          ports:
            - containerPort: {{ .Values.ui.port }}
          securityContext:
            runAsNonRoot: true
            runAsUser: 1000
            readOnlyRootFilesystem: true
            allowPrivilegeEscalation: false
      serviceAccountName: {{ .Release.Namespace }}-sa
      {{- with .Values.global.imagePullSecret }}
      imagePullSecrets:
        - name: {{ . }}
      {{- end }}{{- end }}
