apiVersion: v1
kind: Secret
metadata:
  name: hydra-secrets
  namespace: {{ .Release.Namespace }}
type: Opaque
data:
  DSN: {{ .Values.secrets.dsn | quote }}
  SECRETS_SYSTEM: {{ .Values.secrets.secretsSystem | quote }}
  SECRETS_COOKIE: {{ .Values.secrets.secretsCookie | quote }}
  OIDC_SUBJECT_IDENTIFIERS_PAIRWISE_SALT: {{ .Values.secrets.pairwiseSalt | quote }}