apiVersion: v1
kind: Service
metadata:
  name: hydra-public
  namespace: {{ .Release.Namespace }}
spec:
  type: {{ .Values.service.public.type }}
  selector:
    app: hydra
  ports:
    - name: public
      port: {{ .Values.service.public.port }}
      targetPort: 4444
      protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: hydra-admin
  namespace: {{ .Release.Namespace }}
spec:
  type: {{ .Values.service.admin.type }}
  selector:
    app: hydra
  ports:
    - name: admin
      port: {{ .Values.service.admin.port }}
      targetPort: 4445
      protocol: TCP